/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_SHIFT_PB_H_INCLUDED
#define PB_SHIFT_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _CmdMsg_Command {
    CmdMsg_Command_ZERO = 0,
    CmdMsg_Command_HealthCheck = 1,
    CmdMsg_Command_SetPin = 2,
    CmdMsg_Command_SetByte = 3,
    CmdMsg_Command_Reset = 4,
    CmdMsg_Command_Status = 5
} CmdMsg_Command;

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(2) CmdMsg_data_t;
typedef struct _CmdMsg {
    CmdMsg_Command cmd;
    CmdMsg_data_t data;
} CmdMsg;

/* Helper constants for enums */
#define _CmdMsg_Command_MIN CmdMsg_Command_ZERO
#define _CmdMsg_Command_MAX CmdMsg_Command_Status
#define _CmdMsg_Command_ARRAYSIZE ((CmdMsg_Command)(CmdMsg_Command_Status + 1))

#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define CmdMsg_init_default    \
    {                          \
        _CmdMsg_Command_MIN, { \
            0, { 0 }           \
        }                      \
    }
#define CmdMsg_init_zero       \
    {                          \
        _CmdMsg_Command_MIN, { \
            0, { 0 }           \
        }                      \
    }

/* Field tags (for use in manual encoding/decoding) */
#define CmdMsg_cmd_tag 1
#define CmdMsg_data_tag 2

/* Struct field encoding specification for nanopb */
#define CmdMsg_FIELDLIST(X, a)            \
    X(a, STATIC, SINGULAR, UENUM, cmd, 1) \
    X(a, STATIC, SINGULAR, BYTES, data, 2)
#define CmdMsg_CALLBACK NULL
#define CmdMsg_DEFAULT NULL

extern const pb_msgdesc_t CmdMsg_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define CmdMsg_fields &CmdMsg_msg

/* Maximum encoded size of messages (where known) */
#define CmdMsg_size 6

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif